CREATE TABLE UsersLoginInfo(
    UserId UUID NOT NULL PRIMARY KEY,
    Email VARCHAR UNIQUE NOT NULL,
    UserName VARCHAR NOT NULL,
    PasswordHash VARCHAR NOT NULL,
    PasswordSalt VARCHAR NOT NULL,

    FOREIGN KEY (UserID) REFERENCES UsersInfo(Id) ON DELETE CASCADE); 
